### ISSUE TITLE
activate dev tools

### ISSUE THREAD

**Issue by shelmz** [Lukewh/gathertown-snap#2]
please consider a way to provide dev tools, so one would be able to activate individual mods like these: https://gathertown.fandom.com/wiki/Tools#Hacks

maybe by activating the electron context menu and add some other features for better usability?

**Comment by Lukewh** [comment]
This is now available on `edge`: `snap refresh --edge gathertown`

**Comment by shelmz** [comment]
nice, thank you very much!

**Comment by Lukewh** [comment]
In one of the last two releases I broke some clicking events! Will work on that soon. Fortunately you can use the keyboard for most things
